//#define pairing_wrong_test
//#define pairing_construct
//#define pairing_insert
//#define pairing_get_min
//#define pairing_make
//#define pairing_extract_min
//#define pairing_merge
//#define pairing_solyanka
//#define pairing_construct_comp
//#define pairing_insert_comp
//#define pairing_get_min_comp
//#define pairing_make_comp
//#define pairing_extract_min_comp
//#define pairing_merge_comp
//#define pairing_solyanka_comp
