name: dev-Alexander-soft-heap

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - dev-Alexander-soft-heap

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  head:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: compile!
        run: g++ mytest/src/mytest.cpp mytest/src/mytest_main.cpp include/data_str/test/HeadTest.cpp -I include -I include/data_str -I mytest/include -std=c++17 -o test-head
      - name: Run tests!
        run: ./test-head
  sh-with-head:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: compile!
        run: g++ mytest/src/mytest.cpp mytest/src/mytest_main.cpp include/data_str/test/test-soft-heads/sh-head.cpp -I include -I include/data_str -I mytest/include -std=c++17 -o sh-heads
      - name: Run tests!
        run: ./sh-heads
  buffer:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: compile!
        run: g++ mytest/src/mytest.cpp mytest/src/mytest_main.cpp include/data_str/test/BufferTest.cpp -I include -I include/data_str -I mytest/include -std=c++17 -o test-buf
      - name: Run tests!
        run: ./test-buf
  sh-with-buffer:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: compile!
        run: g++ mytest/src/mytest.cpp mytest/src/mytest_main.cpp include/heaps_with_buf/test/SH_buf_test.cpp -I include -I include/heaps_with_buf -I include/data_str -I mytest/include -std=c++17 -o sh-buf
      - name: Run tests!
        run: ./sh-buf
  softHeap:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: compile!
        run: g++ mytest/src/mytest.cpp mytest/src/mytest_main.cpp include/heapsDesc/test/SH_test.cpp -I include -I include/heaps_with_buf -I include/heapsDesc -I include/data_str -I mytest/include -std=c++17 -o sh-test
      - name: Run tests!
        run: ./sh-test
  softHeap-timetest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: compile!
        run: g++ mytest/src/mytest.cpp mytest/src/mytest_main.cpp src/tests/stress-Big-data/SH.cpp -I include -I include/heaps_with_buf -I include/heapsDesc -I include/data_str -I mytest/include -std=c++17 -o sh-time-test
      - name: Run tests!
        run: ./sh-time-test
  # softHeap-Subtree:
    # # The type of runner that the job will run on
    # runs-on: ubuntu-latest

    # # Steps represent a sequence of tasks that will be executed as part of the job
    # steps:
      # # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2
      # - name: compile!
        # run: g++ mytest/src/mytest.cpp mytest/src/mytest_main.cpp src/tests/sh_subtree.cpp -I include -I include/heapsDesc -I include/heaps_with_buf -I include/data_str -I mytest/include -std=c++17 -o sh-subtree
      # - name: Run tests!
        # run: ./sh-subtree
  block:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: compile!
        run: g++ mytest/src/mytest.cpp mytest/src/mytest_main.cpp include/data_str/test/BlockTest.cpp -I include -I include/heaps_with_buf -I include/data_str -I mytest/include -std=c++17 -o sh-block
      - name: Run tests!
        run: ./sh-block