# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master
      - dev-*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  data-str-BUFFER:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Add permissions for script
        run: chmod u+x all_include.sh
      - name: compile
        run: ./all_include.sh lib/include/test/data-str-test/BufferTest.cpp buffer-test 
      - name: Run tests!
        run: ./buffer-test 
  data-str-HEAD:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Add permissions for script
        run: chmod u+x all_include.sh
      - name: compile
        run: ./all_include.sh lib/include/test/data-str-test/HeadTest.cpp head-test
      - name: Run tests!
        run: ./head-test
  RAM-heaps-PAIRING:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Add permissions for script
        run: chmod u+x all_include.sh
      - name: compile
        run: ./all_include.sh lib/include/test/RAM-test/tests_pairing_heap.cpp ph-RAM-test
      - name: Run tests!
        run: ./ph-RAM-test
  RAM-heaps-SOFT:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Add permissions for script
        run: chmod u+x all_include.sh
      - name: compile
        run: ./all_include.sh lib/include/test/RAM-test/tests_soft_heap.cpp sh-RAM-test
      - name: Run tests!
        run: ./sh-RAM-test
  


  Pairing-Heap:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Add permissions for script
        run: chmod u+x all_include.sh
      - name: compile
        run: ./all_include.sh lib/include/test/HEAP-test/PH_test.cpp PH
      - name: Run tests!
        run: ./PH

  Flower-Heap:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Add permissions for script
        run: chmod u+x all_include.sh
      - name: compile
        run: ./all_include.sh lib/include/test/HEAP-test/FH_test.cpp FH
      - name: Run tests!
        run: ./FH

  Tower-Heap:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Add permissions for script
        run: chmod u+x all_include.sh
      - name: compile
        run: ./all_include.sh lib/include/test/HEAP-test/TH_test.cpp TH
      - name: Run tests!
        run: ./TH

  example-SubTree-Tower-Heap:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Add permissions for script
        run: chmod u+x all_include.sh
      - name: compile
        run: ./run-examples.sh examples/SubTreeTH.cpp TH-ST
      - name: Run tests!
        run: ./TH-ST

  example-SubTree-Pairing-Heap:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Add permissions for script
        run: chmod u+x all_include.sh
      - name: compile
        run: ./run-examples.sh examples/SubTreePH.cpp PH-ST
      - name: Run tests!
        run: ./PH-ST